name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      api_url:
        description: 'API URL to use for the build'
        required: false
        default: 'http://localhost:8080/api'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && 'http://localhost:8080/api' || inputs.api_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build -- --max-warnings=0
        env:
          CI: false
          REACT_APP_API_URL: ${{ env.REACT_APP_API_URL }}

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/craftable-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/craftable-frontend:${{ github.sha }}